"""V4 Stage 1+2 transform with per-subject polarity correction.

Subclass of V4LazyTransformV3 that overrides the polarity-flip decision
(Layer C in the base class) on a per-subject basis using lookup tables
generated by Phase 1 polarity audit:

  per_subject_flip_table.json         (the four development cohorts and the healthy adults)
  per_subject_flip_table_addbio.json  (the seven AddBiomechanics studies)
Both tables are built locally from the source data (docs/training.md).

JSON schema (verified by Phase 2 Task A):
  paper_table   : { cohort:        { subject_id: { channel_name: int } } }
  addbio_table  : { study:         { subject_id: { channel_name: int } } }

Subject-id format is IDENTITY to `Path(npy_path).stem` for BOTH source types:
  - cohort: 'cp_05', 'normal_03', 'vdk_healthy_000', 'vdk_stroke_012', 'SUB01_off'
  - addbio: 'Camargo2021_AB06_split0' (study_subj_split, joined by underscore)

(Note: an earlier prompt specification claimed addbio used SPACE-separator;
Phase 2 Task A audit verified actual JSON uses UNDERSCORE = identity to
dataloader subject_id.)

Flip-decision values per (subject, channel):
   1 -> consistent with vdk_healthy reference, NO flip
  -1 -> inverted, FLIP
   0 -> ambiguous (|PCC| < 0.3 vs reference)
       handled per `ambiguous_policy`:
         'no_flip' (default): treat 0 as 1 (conservative — recommended)
         'flip'             : treat 0 as -1 (aggressive — for ablation)

Fall-back semantics:
  If a subject is NOT present in the per-subject table, this transform
  falls back to the base-class global flip rules (ADDBIO_FLIP_54CH_V3 /
  COHORT_FLIP_54CH_RAW) and logs a warning ONCE per missing subject.
  This preserves backward-compat for any future data added before its
  per-subject audit is run.

Threading note:
  preprocess_before_zscore uses a patch+restore pattern on the base-class
  flip dicts.
  This is safe under standard PyTorch DataLoader behavior (num_workers
  >= 1 uses fork on Linux — each worker has its own forked transform
  instance; no shared mutable state). It is NOT safe if the same
  transform instance is shared across threads in a single process.
  PyTorch DataLoader does not do that.
"""
from __future__ import annotations
import json
import logging
from typing import Dict, List, Optional, Set

import numpy as np

from .transform import V4LazyTransformV3
from .subject_metadata import V4SubjectMetadata


# Sagittal kinematic channel-name -> 54-ch index (verified by Phase 2 Task A.2
# via cross-subject PCC ≥ 0.90 on vdk_healthy reference).
CHANNEL_NAME_TO_54CH: Dict[str, int] = {
    "hip_flex_r":    0,
    "hip_flex_l":    3,
    "knee_flex_r":   6,
    "knee_flex_l":   9,
    "ankle_dorsi_r": 12,
    "ankle_dorsi_l": 15,
}


class V4LazyTransformV3PerSubject(V4LazyTransformV3):
    """Per-subject polarity-aware V4 transform.

    Args:
      metadata: V4SubjectMetadata instance (passed to base).
      global_zstats_path: path to global_zstats.json (passed to base).
      per_subject_table_paper: path to per_subject_flip_table.json
        Loaded if not None; flattened internally into a single subject_id ->
        flip_dict map keyed on the cohort sub-level structure.
      per_subject_table_addbio: path to per_subject_flip_table_addbio.json
      ambiguous_policy: 'no_flip' (default) or 'flip'. See module docstring.
      clip_bound: hard clip range (default 1.5, passed to base).
      bmclab_pelvis_representation: coordinate contract (passed to base).

    Backward-compat:
      If BOTH per_subject_table_paper and per_subject_table_addbio are None,
      this class is functionally identical to V4LazyTransformV3 (uses only
      the global flip tables ADDBIO_FLIP_54CH_V3 / COHORT_FLIP_54CH_RAW).
    """

    def __init__(
        self,
        metadata: V4SubjectMetadata,
        global_zstats_path: Optional[str] = None,
        per_subject_table_paper: Optional[str] = None,
        per_subject_table_addbio: Optional[str] = None,
        ambiguous_policy: str = "no_flip",
        clip_bound: float = 1.5,
        bmclab_pelvis_representation: Optional[str] = None,
    ):
        super().__init__(
            metadata=metadata,
            global_zstats_path=global_zstats_path,
            addbio_flip_override=None,   # keep base global tables as fallback
            cohort_flip_override=None,
            clip_bound=clip_bound,
            bmclab_pelvis_representation=bmclab_pelvis_representation,
        )
        if ambiguous_policy not in ("no_flip", "flip"):
            raise ValueError(
                f"ambiguous_policy must be 'no_flip' or 'flip', got "
                f"{ambiguous_policy!r}"
            )
        self.ambiguous_policy = ambiguous_policy

        # Load + flatten paper table: { cohort: { subj_id: { ch_name: int } } }
        # -> { subj_id: { ch_name: int } }
        self._paper_table: Dict[str, Dict[str, int]] = {}
        if per_subject_table_paper is not None:
            with open(per_subject_table_paper) as f:
                nested = json.load(f)
            for cohort, subj_map in nested.items():
                self._paper_table.update(subj_map)

        # Load + flatten addbio table: { study: { subj_id: { ch_name: int } } }
        self._addbio_table: Dict[str, Dict[str, int]] = {}
        if per_subject_table_addbio is not None:
            with open(per_subject_table_addbio) as f:
                nested = json.load(f)
            for study, subj_map in nested.items():
                self._addbio_table.update(subj_map)

        self._missing_subjects_seen: Set[str] = set()
        self._logger = logging.getLogger(__name__)

    # ------------------------------------------------------------------
    def _per_subject_flip_list(
        self, subject_id: str, source_type: str
    ) -> Optional[List[int]]:
        """Return list of 54-ch indices to flip for this subject, or None
        if subject not present in the per-subject table (signals fallback
        to global rules).
        """
        if source_type == "addbio":
            table = self._addbio_table
        else:
            table = self._paper_table

        flip_dict = table.get(subject_id)
        if flip_dict is None:
            # Subject not in per-subject table: signal fallback
            if subject_id not in self._missing_subjects_seen:
                self._missing_subjects_seen.add(subject_id)
                self._logger.warning(
                    f"[V4LazyTransformV3PerSubject] subject {subject_id!r} "
                    f"(source_type={source_type}) not in per-subject table; "
                    f"falling back to global flip."
                )
            return None

        flips: List[int] = []
        for ch_name, val in flip_dict.items():
            ch_idx = CHANNEL_NAME_TO_54CH.get(ch_name)
            if ch_idx is None:
                # Unknown channel name; skip (defensive — future schema
                # extensions could add e.g. 'pelvis_*' entries)
                continue
            if val == -1:
                flips.append(ch_idx)
            elif val == 0 and self.ambiguous_policy == "flip":
                flips.append(ch_idx)
            # val == 1, or (val == 0 and policy == 'no_flip'): no flip
        return flips

    # ------------------------------------------------------------------
    # Channels audited by Phase 1 (per-subject table covers ONLY these 6)
    _AUDITED_SAGITTAL_KIN_CH54 = set(CHANNEL_NAME_TO_54CH.values())

    def preprocess_before_zscore(
        self,
        arr_54ch: np.ndarray,
        source_name: str,
        source_type: str,
        subject_id: str,
    ) -> np.ndarray:
        """Apply the pre-z-score transform with per-subject polarity.

        Strategy: per-subject decisions REPLACE the global flip rule ONLY for
        the 6 sagittal-kin channels audited by Phase 1 (V4 ch 0,3,6,7,8,9 →
        54-ch 0,3,6,9,12,15). For all OTHER channels (Hip_Mom_Y/Z, Knee_Mom_Z,
        Pelvis, etc.), the global flip rule is preserved unchanged. This
        ensures the audit's narrow scope (6 channels) doesn't accidentally
        un-flip non-sagittal-kin channels that the global table was tuned for.

        Patch+restore on self.{addbio,cohort}_flip is safe under DataLoader
        fork-mode parallelism (each worker has its own forked transform).
        """
        per_subj_audited = self._per_subject_flip_list(subject_id, source_type)
        if per_subj_audited is None:
            # Subject not in table -> use base behavior (global flip)
            return super().preprocess_before_zscore(
                arr_54ch, source_name, source_type, subject_id
            )

        # Compose merged flip list:
        #   - Start with global flip for this source
        #   - Remove ALL audited (sagittal-kin) channels from global
        #   - Add ONLY the audited channels the per-subject table says to flip
        if source_type == "addbio":
            global_flips = self.addbio_flip.get(source_name, [])
        else:
            global_flips = self.cohort_flip.get(source_name, [])
        non_audited_global = [c for c in global_flips
                              if c not in self._AUDITED_SAGITTAL_KIN_CH54]
        merged = sorted(set(non_audited_global) | set(per_subj_audited))

        if source_type == "addbio":
            saved = self.addbio_flip.get(source_name, [])
            self.addbio_flip = dict(self.addbio_flip)
            self.addbio_flip[source_name] = merged
            try:
                return super().preprocess_before_zscore(
                    arr_54ch, source_name, source_type, subject_id
                )
            finally:
                self.addbio_flip[source_name] = saved
        else:
            saved = self.cohort_flip.get(source_name, [])
            self.cohort_flip = dict(self.cohort_flip)
            self.cohort_flip[source_name] = merged
            try:
                return super().preprocess_before_zscore(
                    arr_54ch, source_name, source_type, subject_id
                )
            finally:
                self.cohort_flip[source_name] = saved

    # ------------------------------------------------------------------
    def missing_subjects_report(self) -> List[str]:
        """Sorted list of subject_ids encountered that were not in the
        per-subject table (for trainer-side diagnostic logging)."""
        return sorted(self._missing_subjects_seen)

    def n_subjects_in_table(self) -> Dict[str, int]:
        return {
            "paper": len(self._paper_table),
            "addbio": len(self._addbio_table),
            "total": len(self._paper_table) + len(self._addbio_table),
        }
